//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodOrderLineItem
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int FoodOrder { get; set; }
        public Nullable<decimal> Ammount { get; set; }
    
        public virtual FoodOrder FoodOrder1 { get; set; }
    }
}
