//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transportation
    {
        public int Id { get; set; }
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Input is required.")] public string Name { get; set; }
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Input is required.")] public string Description { get; set; }
        public Nullable<int> BudgetId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> DayId { get; set; }
    
        public virtual Budget Budget { get; set; }
        public virtual Day Day { get; set; }
    }
}
